apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: myfirstrcofnginx
  labels:
    type: frontend
    env: rbhlinux4
spec:
  template:
    metadata:
      name: nginxrs
      labels:
        type: frontend
        env: test
    spec:
      containers:
        - name: dhondujustchill
          image: nginx
  replicas: 3
  selector:
    matchLabels:
      type: frontend
      env: test